 // --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Abbonamento {
	/**
	 * 
	 */
	private Date scadenza;
	/**
	 * 
	 */
	private Spogliatoio spogliatoio;
	/**
	 * 
	 */
	private String idAbbonamento;
	/**
	 * 
	 */
	private int idCliente;
	/**
	 * 
	 */
	private String fasciaOrariaConsentita;
	/**
	 * 
	 */
	private int prezzo;

	/**
	 * 
	 */
	public void rinnova() {
	}

	/**
	 * 
	 */
	public void sospendi() {
	}
}
