// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class abbonamentoCorsi extends Abbonamento {
	/**
	 * 
	 */
	private SalaCorsi salacorsi;
	/**
	 * 
	 */
	private int numCorsiInclusi;

	/**
	 * 
	 * @param corso 
	 */
	public void aggiungiCorso(Corso corso) {
	}
}
