// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class abbonamentoBasico extends Abbonamento {
	/**
	 * 
	 */
	private SalaPesi salapesi;
	/**
	 * 
	 */
	private int limiteIngressiMensili;
}
