// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Cliente {
	
	private String cognome;
	private String nome;
	private String CF;
	private Date dataNscita;
	private String iban;
	private Abbonamento abbonamento;
	private String password;
	
	public void loginApp(String username, String password) {
		
	}
	public void vediAbbonamento() {
		
	}
	public void prenotaConsulenza(Dipendente dip,Date data ) {
		
	}
	public Pagamento effettuaPagamento(int importo, String metodo) {
		return null;
	}
	
}
