// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Corso {
	/**
	 * 
	 */

	/**
	 * 
	 */
	private String tipo;
	/**
	 * 
	 */
	private String durata;
	/**
	 * 
	 */
	private String idCorso;
	/**
	 * 
	 */
	private boolean richiedePrenotazione;
	/**
	 * 
	 */
	private IstruttoreCorso istruttore;
	/**
	 * 
	 */
	/**
	 * 
	 */
	private ArrayList<Cliente> partecipanti;

	/**
	 * 
	 */
	public void aggiungiPartecipante(Cliente c) {
	}

	/**
	 * 
	 */
	public void rimuoviPartecipante(Cliente c) {
	}
}
