// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class IstruttoreCorso extends Dipendente {
	/**
	 * 
	 */
	private String tipoCorsoInsegnato;
	private Corso corso;

	/**
	 * 
	 * @return 
	 * @param cliente 
	 */
	public Corso consigliaCorso(Cliente cliente) {
		return corso ;
	}
}
