// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Macchinario {
	/**
	 * 
	 */
	private String marca;
	/**
	 * 
	 */
	private boolean occupato;
	/**
	 * 
	 */
	private int capacitàCarico;
	/**
	 * 
	 */
	private String nome;

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupato() {
		return true;
	}
}
