// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Nutrizionista extends Dipendente {
	
	private String parcella;
	
	public String creaPianoAlimentare() {
		 return null;
	}
}
