// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class SalaCorsi extends Sala {
	
	
	private int idSala;
	private String orarioCorso;
}
