// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Palestra;

/************************************************************/
/**
 * 
 */
public class Spa extends Sala {
	
	private int numSaune;
	private int numPiscine;
}
