// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Corso {
	/**
	 * 
	 */


	/**
	 * 
	 */
	public String tipo;
	/**
	 * 
	 */
	public String durata;
	/**
	 * 
	 */
	public String idCorso;
	/**
	 * 
	 */
	public boolean richiedePrenotazione;
	/**
	 * 
	 */
	public IstruttoreCorso istruttorecorso;
	/**
	 * 
	 */
	public IstruttoreCorso istruttore;
	/**
	 * 
	 */
	public Cliente partecipanti;

	/**
	 * 
	 */
	public void aggiungiPartecipante() {
	}

	/**
	 * 
	 */
	public void rimuoviPartecipante() {
	}
}
