// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Nutrizionista extends Dipendente {
	
	   private String parcella;

	    public String creaPianoAlimentare() {
	        // TODO: crea e restituisce un piano alimentare
	        return null;
	    }
}
