// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class PersonalTrainer extends Dipendente {
	
	 private String partitaIva;
	 private int anniEsperienza;
     private String certificati;

	    public String creaSchedaAllenamento() {
	        // TODO: genera una scheda di allenamento
	        return null;
	    }
}
