// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class SalaCorsi extends Sala {
	
	   public int idSala;
	    public String orarioCorso;
}
