// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Spa extends Sala {
	
	 private int numSaune;
	 private int numPiscine;
}
